# Generated by Django 2.2.12 on 2021-03-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to='images/')),
                ('gender', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
