# Generated by Django 2.2.12 on 2021-03-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210303_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysiteuser',
            old_name='passwordAgain',
            new_name='password_again',
        ),
    ]
