# Generated by Django 2.2.12 on 2021-03-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210303_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysiteuser',
            name='password_again',
        ),
    ]
